### ISSUE TITLE
Listener Rules

### ISSUE THREAD

**Issue by colincoleman** [TeliaSoneraNorge/divx-terraform-modules#97]
As a developer I would like an easy way (using terraform modules) to be able to use path based routing to add my micro service to an existing load balancer and existing HTTP or HTTPS listener

So that I can have many micro-services behind a single load balancer using standard ports.

**Comment by colincoleman** [comment]
1. If you create a load balancer and a listener then you need a target group to set as the default target.
My solution (hack) for this has been to create a "default-empty" target group that in effect returns a 403

2. Each listener rule requires a unique priority value - setting and changing these priorities could easily result in 2 listener rules with the same priority and create an error.  There are many difficult hacks that could be done to address this.  A simple option could be to keep a list of the attached listener rules and their priorities in the README file of the repo with the listener (the common infrastructure)

**Comment by itsdalmo** [comment]
Cool. I think attempting to use [listener](https://www.terraform.io/docs/providers/aws/r/lb_listener.html) and [listener rule](https://www.terraform.io/docs/providers/aws/r/lb_listener_rule.html) interchangeably in the same module would be a bit hacky, so it'd be better to make a separate module. If the new module followed the same pattern as the `target` module (by creating a target group + N listener rules), it would be opinionated in the way that you can't create new rules for existing target groups - but this seems like an anti-pattern anyway.

At the same time, I think it would make sense to rename the `target` module to `listener` and then create a new `listener/rule` under that? I think conceptually it makes more sense since what the module does is to create one or more listeners which map to a single target group, and encourages us to specify all listeners/listener rules for a single target in the same place.

**Comment by itsdalmo** [comment]
Fixed in latest commit
